language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - "pip install cython"
  - "sh ./install-deps.sh"
  - "CPPFLAGS="-fkeep-inline-functions -fno-inline -fprofile-arcs -ftest-coverage --coverage -O0" LDFLAGS="--coverage" python setup.py build"
  - "python setup.py install"
# command to run tests
script: 
    - "cd Tests && make testpython"
    - "cd Tests/coverage && make coverage"
